### ISSUE TITLE
Hovering tokens with wildcard image paths shows only the base path image

### ISSUE THREAD

**Issue by MarlQ** [Eriku33/Foundry-VTT-Image-Hover#1]
To reproduce, simply create a token with image path e.g. soldier_*.png (with image soldier_1.png, soldier_2.png in the folder).
The hover will only show the base path image, in this example soldier_1.png.

**Comment by Eriku33** [comment]
Thanks for reporting this issue! This should now be fixed in the latest release (v.1.0.5).
