### ISSUE TITLE
Display art after hover delay

### ISSUE THREAD

**Issue by flamableconcrete** [Eriku33/Foundry-VTT-Image-Hover#11]
Not sure if this is interesting to you or not, but it would be cool if you could have a setting where the art would only appear after X seconds instead of immediately. Double bonus points if it were configurable separately by individual clients and not a global setting set by the Gamemaster.

Regardless, super awesome plugin - thanks for putting it out here! I love it!

**Comment by flamableconcrete** [comment]
I'm not going to pretend like I know what I'm doing, since I've never created a module myself, but two seconds after creating this issue I came across this other 46 line module that sets up something with settings which are configurable per player, so maybe it could be a good reference for implementing something like my suggestion?

https://github.com/mrkwnzl/disable-mouse-wheel-sliders-foundryvtt

**Comment by Doresain** [comment]
+1 to this good suggestion, if you find yourself mucking with this module again this would be a great enhancement.

**Comment by Eriku33** [comment]
Hi all,

This is a new feature in v2.0.1 of Image hover, you will need to update to v9 Foundry though for compatibility.
