### ISSUE TITLE
[Enhancement] Setting to avoid showing art for placeable object tokens

### ISSUE THREAD

**Issue by Doresain** [Eriku33/Foundry-VTT-Image-Hover#12]
First off, very cool module, thank you!

Tokens are sometimes used in foundry to control placeable objects (using Token Attacher or otherwise). In these cases it may not be desirable to show the actor's art for that token on hover. For example, in this screenshot the token is used to control the placement and text of a sign placed in the scene:
![image](https://user-images.githubusercontent.com/26096062/113943110-d5b23480-97b6-11eb-829d-7eceddeff2fa.png)

You can see in the bottom right the grainy, duplicative art for the sign that shows up on hover. It would be cool if one could control if a token showed art on hover or not. I can think of two ways to accomplish this:

1) The more complicated but more flexible way would be to add a checkbox to the Image tab of token settings that controls a 'show art?' boolean that could default to true and you could check on hover before rendering the art.

2) The easier way to do it (which is what the [Health Estimate](https://github.com/mclemente/healthEstimate) module does) is to add a setting to simply avoid rendering the art if the token's actor has 0 max HP. This is less flexible (some folks may want to show art for placeable objects in some cases but not others) but would generally get the job done.

**Comment by MalakanC** [comment]
Just came to post a similar enhancement. I have a token that is a `Loot Sheet NPC 5e` actor that I don't want my players to see pop up with this module.

It would be nice to have a toggle per actor to disable this feature.

Thank you!

**Comment by Eriku33** [comment]
Hi all,

This is a new feature in v2.0.1 of Image hover, you will need to update to v9 Foundry though for compatibility.
