### ISSUE TITLE
Not compatable with 8.x

### ISSUE THREAD

**Issue by Kylarfi** [Eriku33/Foundry-VTT-Image-Hover#13]
Is there any plans to update this module for the newest foundry update?  It's one of my favorites!

**Comment by gcolgate** [comment]
I am not the author of the module but I've fixed this issue (it's a  one line change  -on line 13 of image-hover.js
Add this line 
let DEFAULT_TOKEN = "";                                             // Quick not good fix for DEFAULT_TOKEN no longer existing

**Comment by gcolgate** [comment]
gcolgate@52711c5
Here is the commit. I am not sure how to make it visible to the author. It's in a fork

**Comment by Eriku33** [comment]
You will also need to install the keybind lib module (https://foundryvtt.com/packages/keybind-lib)
