### ISSUE TITLE
I have fixed the incompatibility with 8.1, it is a one line change

### ISSUE THREAD

**Issue by gcolgate** [Eriku33/Foundry-VTT-Image-Hover#14]
Change line 13 to let DEFAULT_TOKEN = "";                                             // Quick not good fix for DEFAULT_TOKEN no longer existing

I am currently stuck figuring out how to add a branch that can be cherry picked in github

**Comment by gcolgate** [comment]
https://github.com/gcolgate/Foundry-VTT-Image-Hover/commit/52711c53b8afefc332cde12d2d98165a3ca8ecb1
Here is the commit. I am not sure how to make it visible

**Comment by amcvfx** [comment]
I tried using the version you posted but I get this error:

![image](https://user-images.githubusercontent.com/35099081/121433652-3525ef80-c974-11eb-9f87-c2a8cc05d185.png)

**Comment by Eriku33** [comment]
Hello everyone!

Sorry for the delay, just been enjoying life at the moment. Haven't used Foundry for a very long time.
Newest release should solve some problems (1.1.8), let me know if I missed something.

**Comment by gcolgate** [comment]
That's the error message  I fixed I hope you fixed it correctly!  I just
defined that missing symbol as ""

**Comment by Eriku33** [comment]
Thanks gcolgate,

**Comment by Eriku33** [comment]
You will also need to install the keybind lib module (https://foundryvtt.com/packages/keybind-lib)

**Comment by gcolgate** [comment]
thanks
