### ISSUE TITLE
Deprecated message

### ISSUE THREAD

**Issue by jasonckramer** [Eriku33/Foundry-VTT-Image-Hover#15]
Hello!

Awesome module! I've noticed the following message coming up in the console every time I mouse over a token. Figured it was something that should be noted.

![26 06 2021_14 14 15_REC](https://user-images.githubusercontent.com/22718298/123522157-9692d180-d689-11eb-9af1-eac027629a65.png)

**Comment by Fridan99** [comment]
The same....

**Comment by Eriku33** [comment]
Thanks, this shouldn't of caused any actual issues. The newest release (V2.0.0) should be compatible with Foundry VTT v9 if you wish to update.
