### ISSUE TITLE
Feature Request: Token Art If Unlinked

### ISSUE THREAD

**Issue by tjlanza** [Eriku33/Foundry-VTT-Image-Hover#17]
Foundry VTT 0.8.9, Image Hover 1.1.8

The "Art on hover" setting has an option to show the token art on wildcard. Presumably, this is intended to be used when a actor represents an NPC with multiple token art variations but no unique or interesting character artwork. Modules like [Token HUD Wildcard](https://github.com/javieros105/FVTT-TokenHUDWildcard) leverage the wildcard feature to allow manually selecting token art from the wildcard list. This opens up the possibility of players and similarly unique characters to have multiple token art pieces, and the players selecting between them on the fly.

![image](https://user-images.githubusercontent.com/21128724/139063556-a8181589-49d3-4a62-bc00-13417ecc6f81.png)

However, when using wildcards in this fashion, the available "Token Art If Wildcard" option (which works for NPCs) means the (generally more complete) character artwork won't be seen. I would like to see an additional option here: "Token art if unlinked". Linked actors (typically PCs & unique NPCs) would then show the selected character art, unlinked generic actors would show the token art.

**Comment by Eriku33** [comment]
Hi Tjlanzaz

This is a new feature in v2.0.1 of Image hover, you will need to update to v9 Foundry though for compatibility.
