### ISSUE TITLE
Show to All Players Hotkey

### ISSUE THREAD

**Issue by AurelTristen** [Eriku33/Foundry-VTT-Image-Hover#20]
Sorry, I don't know how to mark this as a feature request!
If a second keybind could allow the hovered token's artwork to display to all players (maybe with its own position setting), this would be a very handy way to instantly communicate which NPC is speaking. In a conversation with several NPCs, things can get confusing quickly, and the built in 'show artwork to players' is too slow and bulky to be used for this task.

**Comment by Eriku33** [comment]
Hello you might be looking for this module called [Show art/ TokenHUDArtButton](https://foundryvtt.com/packages/token-hud-art-button). I've never used it before but it might do what you want.

**Comment by davidhawbecker** [comment]
I use the Show Art module which works pretty well, but I would like to second this suggestion for your module if it's even feasible. The difference is subtle but being able to hover over a token and have it show to all players and then disappear from their view when the GM isn't hovering over the token would stream like the process quite a bit. Of course I don't have any idea how feasible this is from a technical standpoint so maybe it's asking a bit much. Either way I have loved this module for quite a while so thank you for the great work.

**Comment by Eriku33** [comment]
Hello all,

The [latest release](https://github.com/Eriku33/Foundry-VTT-Image-Hover/releases/tag/2.0.5) will implement this feature.
This feature does not have it's own position placement setting nor will the art disappear when the GM isn't hovering over the token.

Currently the GM can set a key bind and use this key bind while hovering over a token to show all connect users art. The art will be shown for 6 seconds (can be changed in game master module settings) and will disappear after 6 seconds unless the key is pressed again on a token thus repeating the process.

There are some limitations such that users must have Image Hover enabled and be on the same scene as the game master.
Art will be shown even if the users do not have the required actor permissions or "Hide art for specific token" is checked on the token.

I hope the way I implemented this feature is sufficient for your needs. I'm really glad that you like my module!

**Comment by Eriku33** [comment]
Just want to first confirm that you have **assign a keybind to show all users art** and when you hover and press that key over a character it stays on your screen for 6 seconds?
![image](https://user-images.githubusercontent.com/47860010/203654923-575599f8-5c2d-48a7-bd09-7045cc8ef367.png)

**Comment by AurelTristen** [comment]
I don't know if this helps, but I'm on v10,290 (5e 2.0.3) and it is working properly for me (and replicating to clients).
