### ISSUE TITLE
Disable for some tokens

### ISSUE THREAD

**Issue by brunocalado** [Eriku33/Foundry-VTT-Image-Hover#24]
Hi. Great module.

Can you add an option in the token settings to disable token hover? 

It's useful when you have tokens you don't want to show art.
- 3D models with the 3d module
- Item piles
- etc

**Comment by Eriku33** [comment]
Hi Brunocalado,

This is a new feature in v2.0.1 of Image hover, you will need to update the module, glad you like my module!
