### ISSUE TITLE
Hide Image Hover Art not saving

### ISSUE THREAD

**Issue by brunocalado** [Eriku33/Foundry-VTT-Image-Hover#27]
Hi,

This button works, but it resets all the time, and I have to check it again.
![image](https://user-images.githubusercontent.com/4999783/152840578-c3485933-e2e4-4814-bab6-d02418b6eb61.png)

**Comment by Eriku33** [comment]
Hi Brunocalado,

I believe this happens when you move a token from the actors directory to the canvas but the token setting is not displayed correctly (even though it is working). 
I will fix this for next release, let me know if I misunderstood or if you're experiencing a different bug.

Thanks!
