### ISSUE TITLE
Feature Request: Hover only if key is pressed

### ISSUE THREAD

**Issue by Norc** [Eriku33/Foundry-VTT-Image-Hover#3]
This looks really great, but I have concerns about it getting in the way or being distracting, particularly when I'm working in the bottom left corner of the map or setting up a combat as a GM and not wanting to be distracted.

Would it be possible to add a keydown check also? So, only show the image hover if you mouse over it *and* have shift, ctrl, or a key like i or s or something pressed? Ideally this could be configurable with a setting.

Thanks, it looks super great, and I love ways to make the art more accessible to players.

**Comment by Eriku33** [comment]
Hello Norc!

I've added this feature in the latest release (v1.0.8). You will need to enable the key bind requirement in the module settings and there's a option to change the key bind, the default is v.

**Comment by Norc** [comment]
Fantastic! I'm going to use this in my Monday game. Thanks so much for the amazing module and response time lol!
