### ISSUE TITLE
Keybind not working

### ISSUE THREAD

**Issue by 9ryex5** [Eriku33/Foundry-VTT-Image-Hover#31]
I've been trying to use the keybind feature of this module but it's not working.
Getting this problem in console: 
![image](https://user-images.githubusercontent.com/43207603/163062992-9520f6f3-9403-4084-b204-06d55f1d599e.png)

**Comment by Eriku33** [comment]
Hi 9ryex5,

Thanks for bringing this to my attention!
I have a pushed a hotfix release to fix this.
Please update and thanks again!

**Comment by 9ryex5** [comment]
Thanks :)
