### ISSUE TITLE
Please allow an option to disable debug, this module spams the console and makes debugging macros more difficult

### ISSUE THREAD

**Issue by TogaParty** [Eriku33/Foundry-VTT-Image-Hover#32]
Please allow an option to disable debug, this module spams the console and makes debugging macros more difficult

**Comment by Eriku33** [comment]
Please could you expand a bit on this?
What message are you seeing?
The only time the module puts anything in the console is when you hover over a token (apart from the initial loading of world).

**Comment by Eriku33** [comment]
closing this until further information arises
