### ISSUE TITLE
Error while moving and hovering over tokens

### ISSUE THREAD

**Issue by Dialectikal** [Eriku33/Foundry-VTT-Image-Hover#34]
I've been seeing this error occasionally while moving a token and hovering over it or near it at the same time:
![image](https://user-images.githubusercontent.com/31572084/165197142-a5915ca5-b41a-491a-8fd1-6da20f94b903.png)

I'm not sure how to troubleshoot the issue and it is somewhat difficult to recreate consistently. I've managed to recreate it by simply moving a token back and forth and hovering over its space.

**Comment by esheyw** [comment]
Hi, just confirming this is still a thing in release. Seems to reliably happen every time I close a dialog.

**Comment by Eriku33** [comment]
Hello everyone,

There are some slight incompatibilities with a module called Chat Portrait.
Though this issue should now be fixed in the latest update.
Thanks for your help!
