### ISSUE TITLE
Image Hover not working with version 9x

### ISSUE THREAD

**Issue by medeiros961030** [Eriku33/Foundry-VTT-Image-Hover#41]
after update the module stopped working in version 9x

![image](https://user-images.githubusercontent.com/112792783/188297515-d02366a5-7c4e-4ee0-8252-88fa918cf24b.png)

**Comment by Eriku33** [comment]
Hello,

Apologies this was a mistake on my part and should only effect the few hundred people who updated in the last 20 hours.
Please uninstall and reinstall the module and the correct version will be used.

Thanks for bringing this to my attention,

Eric
