### ISSUE TITLE
Not working in previous versions

### ISSUE THREAD

**Issue by NikkitaAurion** [Eriku33/Foundry-VTT-Image-Hover#45]
it only downloads the version 10 of the image hover for me and broke doesn't work anymore please fix I like this module

**Comment by Eriku33** [comment]
Hello,

Any chance you can clarify which version of Foundry you are on? I assume it's v11?

Thanks 👍

**Comment by NikkitaAurion** [comment]
Iam using Version 9 and when i go to DL on the modules of the app it downloads the 10 version instead

**Comment by Eriku33** [comment]
Any chance you can try uninstalling and reinstalling the module?

Sorry for the inconvenience.

**Comment by NikkitaAurion** [comment]
I have many different times but I just when to the old updates and copied the link that way but the manifest for version 9 is auto getting version 3 which is for version 10

**Comment by Eriku33** [comment]
Thanks for letting me know, I will look into this.

**Comment by Eriku33** [comment]
Hello, any chance you can reinstall one last time? it should work from now on.
If this doesn't solve the issue, can you please let me know the exact Foundry version you are on please.

Thanks

**Comment by NikkitaAurion** [comment]
I am on version 9.80 
All i did was go onto the previous releases on github and copied the address of the manifest of the one that would work best with my version

**Comment by Eriku33** [comment]
I would recommend using the in-built Foundry interface instead of looking at github releases as Foundry would select the latest compatible version for you automatically. I also assume you are on Foundry 9.280 as 9.8 doesn't exist.
![image](https://user-images.githubusercontent.com/47860010/218284431-a950e40a-060c-4326-bfb5-78b9ce8d24a6.png)

In summary you should either reinstall Image Hover within the Foundry app or use this manifest json (if you are on Foundry v9.280).
https://github.com/Eriku33/Foundry-VTT-Image-Hover/releases/download/2.0.6/module.json

If you still have issues, you can add me on discord (Eriku#2108) and we can setup a call sometime.

**Comment by NikkitaAurion** [comment]
I tried it off the foundry program and the website and both gave me the wrong version which is why i went to github in the first place

**Comment by Eriku33** [comment]
That's totally understandable and logical, it was a fault on my part and I thank you for bringing it to my attention. Let me know if the issue still persists as I can't seem to replicate the issue.

**Comment by NikkitaAurion** [comment]
i will try it after my game session for yah ^#^

**Comment by NikkitaAurion** [comment]
![Current](https://user-images.githubusercontent.com/97050321/218292074-e6a080a1-087e-4fc4-ba82-d24c8eb511d3.PNG)
^Before i download via Foundry  this is what it should be
now i try to download off foundry
![image](https://user-images.githubusercontent.com/97050321/218292100-7cd87c57-b5e7-4821-92c5-d9c74053d457.png)
![image](https://user-images.githubusercontent.com/97050321/218292119-574f42fc-20ad-4504-8500-1861830eb5be.png)
![image](https://user-images.githubusercontent.com/97050321/218292124-c9bc4c0f-8342-416a-835f-30683498ebbd.png)

**Comment by Eriku33** [comment]
Thanks for the screenshots! They were very helpful for me. Fingers crossed, should be fixed now 😅.

**Comment by NikkitaAurion** [comment]
![image](https://user-images.githubusercontent.com/97050321/218319270-e58a2b9f-763b-47a4-b779-beb1824b3531.png)

**Comment by Eriku33** [comment]
5th time's the charm?

**Comment by NikkitaAurion** [comment]
it's Fixed!! whooo

**Comment by Eriku33** [comment]
Thanks for the consistent cooperation!

**Comment by NikkitaAurion** [comment]
Anytime Glad to help
