### ISSUE TITLE
'.JPG' images don't show

### ISSUE THREAD

**Issue by amcvfx** [Eriku33/Foundry-VTT-Image-Hover#5]
Loving this module!
I'm having an issue though, where images saved with certain extensions don't show. So far I've noticed jpegs saved as '.JPG' (using capitals) don't work. Saving the same image as .webp fixed it though. Not sure if this is the cause or not. I'm on The Forge.

**Comment by Eriku33** [comment]
Hello amcvfx!

Thanks for providing the extra information, it was very helpful! Glad you enjoy the module.
Updating the module should fix the problem (v1.0.9).
Let me know if the problem persists.
