### ISSUE TITLE
Version 11. Modules updating

### ISSUE THREAD

**Issue by pplurueda** [Eriku33/Foundry-VTT-Image-Hover#50]
When updating modules in Foundry version 11, the following messages always appear.

<img width="202" alt="image" src="https://github.com/Eriku33/Foundry-VTT-Image-Hover/assets/82481289/84329e02-fdd4-4c72-bd64-34572d092d66">

<img width="169" alt="image" src="https://github.com/Eriku33/Foundry-VTT-Image-Hover/assets/82481289/08d83ba6-1bea-4401-b72e-9931c4f9328d">

**Comment by farling42** [comment]
This is most likely because the "v" appears in the listing on the foundry package web site.

**Comment by Talanor** [comment]
It somehow fixed itself for me
