### ISSUE TITLE
V11: Hover detected even if window on top of token

### ISSUE THREAD

**Issue by farling42** [Eriku33/Foundry-VTT-Image-Hover#51]
When a journal is covering several tokens, moving the cursor within the border of the window will trigger the image hover on tokens that are on the canvas beneath the journal.

**Comment by farling42** [comment]
This might be related to something I read on discord. Something about the newer version of PIXI always processing events despite a window above it also using the event.

**Comment by Eriku33** [comment]
I can't recreate the issue, am I misunderstanding something?
![Animation](https://github.com/Eriku33/Foundry-VTT-Image-Hover/assets/47860010/775ae388-94dd-4b27-8050-473e18a2ca9f)

**Comment by farling42** [comment]
I think I raised this on Foundry 305 or earlier, and it was a bit in core event handling rather than your module.

It is not a problem with core 11.307
