### ISSUE TITLE
Image Hover for Stream View

### ISSUE THREAD

**Issue by Conradhowlf** [Eriku33/Foundry-VTT-Image-Hover#56]
I record my sessions using Stream View and I wanted the images to show on the Stream View client when I hover in the DM screen, is there a way to do that?

**Comment by Eriku33** [comment]
Hi Conrad,
Currently the easiest way to do that would be to have a game master set a keybind in the image hover settings (show art to all users). Then as a game master hovering over a token and pressing that keybind. This would show the artwork to all users. Assuming I understand the stream view module from a quick read.
