### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by MSAbaddon** [Eriku33/Foundry-VTT-Image-Hover#8]
Currently, your module generates some error messages whenever a token is placed on a scene.

![image](https://user-images.githubusercontent.com/66370966/106504436-36777500-64c7-11eb-8c69-db50cc398ba6.png)

**Comment by Eriku33** [comment]
Hello MSAbaddon,

I struggled to reproduce these errors in my game, hopefully the newest release will fix these issues

**Comment by MSAbaddon** [comment]
Hi,
nearly forgot to give you feedback - you fix worked wonders - no error messages anymore :-)
